'use strict';
const $=s=>document.querySelector(s), KEY='nynth-studio-demo-v1';
const cloud='https://res.cloudinary.com/dqouigbvm/image/upload/f_auto,q_auto,w_800/';
const images={campaign:cloud+'v1790062933/dhqkyrnzt5334bzekhev.jpg',spyder:cloud+'v1784496152/xrrdqjclbt7azmjvc6c7.jpg',black:cloud+'v1783796871/vk8d2pfccu500f8xnj4z.jpg',white:cloud+'v1790062118/ib9s1oh4rt2dotaxpn7z.jpg',red:cloud+'v1783796006/ced9jfcczep8h24h7ggj.jpg',model:cloud+'v1775059396/y2wbramtww8ha9wrndri.jpg'};
const initial={brand:{name:'NYNTH World',tagline:'Stay Above.',intro:'The pieces. The people. The point of view.',editor:'Newman Yange'},sections:[{id:'people',title:'Our Stories',description:'The founder, the ambassador, the culture.',visible:true},{id:'pieces',title:'Behind the Pieces',description:'Product stories with a point of view.',visible:true},{id:'community',title:'Community',description:'The people behind the style.',visible:true},{id:'culture',title:'Style meets culture',description:'Music, expression and life beyond the clothes.',visible:true}],media:Object.entries(images).map(([id,url])=>({id,url,name:({campaign:'Winners campaign',spyder:'Michael Spyder',black:'Winners · Black',white:'NYNTH · White',red:'Winners · Red',model:'NYNTH campaign portrait'})[id]})),stories:[
{id:'newman',title:'Newman: the vision behind NYNTH.',category:'Our Stories',author:'Newman Yange',summary:'Fashion, music, and the belief behind Stay Above.',body:'Every brand begins with a point of view. This is the space for Newman’s story: what drives him, how music and fashion meet, and what Stay Above means to him.\n\nDraft placeholder — Newman’s own words will bring this story to life.',image:'newman',status:'Draft',featured:true},
{id:'winners',title:'The world only needs winners.',category:'Behind the Pieces',author:'Newman Yange',summary:'A statement you wear. A mindset you live.',body:'Some pieces say everything before you say a word. The Winners tee puts a bold message at the centre of an everyday silhouette.\n\nStart with the statement. Keep the rest personal: loose denim, your favourite trainers, a cap you reach for without thinking.',image:images.campaign,status:'Published',featured:true},
{id:'michael-spyder',title:'Michael Spyder: journey across Africa.',category:'Our Stories',author:'NYNTH Editorial',summary:'The passion and belief behind Stay Above.',body:'Michael Spyder is a NYNTH ambassador. This space will follow his journey across Africa through the lens of passion, strength and belief.\n\nSample introduction — journey details and final writing to come.',image:images.spyder,status:'Published',featured:false},
{id:'uniform',title:'Same statement. Your own uniform.',category:'Behind the Pieces',author:'NYNTH Editorial',summary:'Let the tee do the talking. Three ways to make it yours.',body:'One graphic tee can move through different versions of your day. Try relaxed denim, straight trousers, or an open overshirt.\n\nPersonal style happens in the choices between the pieces.',image:images.black,status:'Published',featured:false},
{id:'white',title:'A fresh take on the white tee.',category:'Behind the Pieces',author:'NYNTH Editorial',summary:'Quiet colour. An unmistakable identity.',body:'A white tee is a starting point, not a finished outfit. Pair it with faded denim, darker trousers or a bright accessory to shift the mood.',image:images.white,status:'Published',featured:false},
{id:'details',title:'Wear the statement.',category:'Behind the Pieces',author:'NYNTH Editorial',summary:'The Winners tee: bold lettering and a message that stands out.',body:'The Winners tee puts its message front and centre: The World Only Needs Winners.\n\nWear it with simple denim or plain trousers to give the graphic room.',image:images.red,status:'Published',featured:false},
{id:'culture',title:'The world around NYNTH.',category:'Culture',author:'Newman Yange',summary:'A shared perspective. A culture in motion.',body:'A space for the people and creative expression that give NYNTH its voice.\n\nAdd your culture story here.',image:images.campaign,status:'Draft',featured:false},
{id:'nynth-perspective',title:'A personal take on NYNTH.',category:'Our Stories',author:'NYNTH Editorial',summary:'The person behind the look.',body:'A black NYNTH cap, a dark jacket and layered accessories give this campaign look its shape.\n\nThe featured person’s name and story will be supplied by Newman.',image:images.model,status:'Draft',featured:false}],submissions:[{id:'sample-1',title:'One tee, three ways.',author:'Sample contributor A',category:'Behind the Pieces',summary:'A street-style photo diary exploring three ways to wear the Winners tee.',body:'Sample submission for review. This would include the contributor’s complete story and photography.',image:images.black,status:'Pending'},{id:'sample-2',title:'The soundtrack to my city.',author:'Sample contributor B',category:'Culture',summary:'Music, movement and the outfits that connect them.',body:'Sample submission for review. This is where the contributor’s writing would appear.',image:images.campaign,status:'Pending'}],cover:'winners'};
let state=structuredClone(initial),view='overview',filter='All',query='',uploadMode='library',coverImage='',toastTimer;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&Array.isArray(saved.stories)&&Array.isArray(saved.media)&&Array.isArray(saved.sections)&&Array.isArray(saved.submissions)&&saved.brand)state=saved}catch{}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeImage(src){return typeof src==='string'&&(/^(https?:\/\/)/i.test(src)||/^data:image\/(jpeg|png|webp);base64,/i.test(src))?src:''}
function photo(src,cls='',alt='Story cover'){if(src==='newman')return `<div class="${cls} newman-portrait" role="img" aria-label="Portrait of Newman Yange"></div>`;const url=safeImage(src);return url?`<img class="${cls}" src="${esc(url)}" alt="${esc(alt)}" loading="lazy">`:`<div class="${cls}" role="img" aria-label="No cover image"></div>`}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{toast('Browser storage is full or unavailable. This change lasts only until you leave.');return false}}
function heading(kicker,title,sub,action=''){return `<div class="page-heading reveal"><div><div class="overline">${kicker}</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function badge(status){return `<span class="badge ${status==='Draft'?'draft':status==='Pending'?'review':''}">${esc(status)}</span>`}
function table(stories){return `<div class="table-wrap"><table><thead><tr><th>STORY</th><th>SECTION</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>${stories.map(s=>`<tr><td><div class="table-story">${photo(s.image,'thumb',s.title)}<div><strong>${esc(s.title)}</strong><small>${esc(s.author)}</small></div></div></td><td>${esc(s.category)}</td><td>${badge(s.status)}</td><td><div class="row-actions"><button class="star" data-action="feature" data-id="${esc(s.id)}" aria-label="${s.featured?'Unfeature':'Feature'} ${esc(s.title)}" aria-pressed="${s.featured}">${s.featured?'★':'☆'}</button><button data-action="edit" data-id="${esc(s.id)}">Edit</button><button data-action="preview" data-id="${esc(s.id)}" aria-label="Preview ${esc(s.title)}">↗</button></div></td></tr>`).join('')}</tbody></table>${!stories.length?'<div class="empty">No stories found. Try a different filter or write something new.</div>':''}</div>`}
function coverCard(){const s=state.stories.find(s=>s.id===state.cover)||state.stories[0];return `<div class="cover-card">${photo(s.image,'',s.title)}<span class="cover-tag">HOMEPAGE PREVIEW</span><div class="cover-content"><div class="overline">THE COVER STORY / ${esc(s.category)}</div><h3>${esc(s.title)}</h3><button data-action="edit" data-id="${esc(s.id)}">Make it yours ↗</button></div></div>`}
function overview(){const published=state.stories.filter(s=>s.status==='Published').length,pending=state.submissions.filter(s=>s.status==='Pending').length;return heading('YOUR WORLD. YOUR WORDS.','Welcome back, Newman.','Let’s give the world something to feel.','<button class="button" data-action="new">＋ Write a story</button>')+`<div class="stats">${[[state.stories.length,'Total stories','Your growing journal','▤'],[published,'Published','Sample published stories','↗'],[state.stories.length-published,'In the making','Drafts waiting for your touch','✎'],[pending,'To review','Sample community submissions','↙']].map((x,i)=>`<div class="stat reveal" style="--i:${i+1}"><div class="stat-label">${x[1]}</div><span class="stat-symbol">${x[3]}</span><div class="stat-num">${x[0]}</div><small>${x[2]}</small></div>`).join('')}</div><div class="dashboard-grid reveal" style="--i:3"><section class="panel"><div class="panel-head"><div><h2>In the spotlight.</h2><p>The first story your world sees.</p></div><button class="text-button" data-action="go" data-target="homepage">Manage homepage ↗</button></div>${coverCard()}</section><div><section class="panel"><div class="panel-head"><h2>Make your next move.</h2></div><div class="quick-list">${[['✎','Write a story','Turn a thought into something worth reading.','new',''],['↑','Add to your visual world','Upload a photo to the demo library.','upload',''],['▦','Curate the homepage','Decide what deserves the spotlight.','go','homepage']].map(x=>`<button class="quick-item" data-action="${x[3]}" data-target="${x[4]}"><span class="quick-icon">${x[0]}</span><span><strong>${x[1]}</strong><small>${x[2]}</small></span><span>↗</span></button>`).join('')}</div></section><div class="journal-note"><div class="overline">A NOTE FROM THE STUDIO</div><span class="spark">✳</span><h3>More than what we wear.</h3><p>Passion. Strength. Belief. Let every story carry a little of what NYNTH stands for.</p></div></div></div><section class="panel recent reveal" style="--i:4"><div class="panel-head"><div><h2>On your desk.</h2><p>A few stories to pick up where you left off.</p></div><button class="text-button" data-action="go" data-target="stories">All stories ↗</button></div>${table(state.stories.slice(0,4))}</section>`}
function storiesView(){return heading('THE JOURNAL','Every story starts here.','Write, refine, and decide what goes out into your world.','<button class="button" data-action="new">＋ Write a story</button>')+`<div class="toolbar reveal"><input class="search" id="search" type="search" placeholder="Search stories or authors…" aria-label="Search stories" value="${esc(query)}"><div class="tabs" role="group" aria-label="Filter by status">${['All','Published','Draft','Featured'].map(f=>`<button data-action="filter" data-id="${f}" class="${filter===f?'active':''}" aria-pressed="${filter===f}">${f}</button>`).join('')}</div></div><section class="panel reveal" id="story-results">${filteredTable()}</section>`}
function filteredTable(){return table(state.stories.filter(s=>(filter==='All'||filter==='Featured'&&s.featured||s.status===filter)&&`${s.title} ${s.author}`.toLowerCase().includes(query.toLowerCase())))}
function homepage(){return heading('YOUR FRONT PAGE','Set the scene.','Arrange the sections, choose the cover, and put your stories first.')+`<div class="homepage-layout reveal"><div><section class="panel"><div class="panel-head"><div><h2>The cover story</h2><p>Choose the opening story in this demo.</p></div></div><div style="padding:0 22px 22px"><label for="cover-select">Featured cover</label><select id="cover-select">${state.stories.filter(s=>s.status==='Published').map(s=>`<option value="${esc(s.id)}" ${s.id===state.cover?'selected':''}>${esc(s.title)}</option>`).join('')}</select></div></section><div class="panel-head"><div><h2>A little order. A lot of you.</h2><p>Move sections up or down. Hide what isn’t ready.</p></div></div><div class="section-list">${state.sections.map((s,i)=>`<div class="section-row"><span class="section-number">0${i+1}</span><div class="section-info"><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p></div><div class="section-controls"><button class="small-btn" data-action="move-up" data-id="${s.id}" aria-label="Move ${esc(s.title)} up" ${i===0?'disabled':''}>↑</button><button class="small-btn" data-action="move-down" data-id="${s.id}" aria-label="Move ${esc(s.title)} down" ${i===state.sections.length-1?'disabled':''}>↓</button><button class="small-btn" data-action="toggle-section" data-id="${s.id}" aria-pressed="${s.visible}" aria-label="Show ${esc(s.title)}">${s.visible?'On':'Off'}</button></div></div>`).join('')}</div><p class="form-hint">Featured stories: use the ★ beside any story. Newman’s featured stories appear first in this preview.</p></div><div><p class="overline" style="margin-bottom:12px">YOUR HOMEPAGE / MINI PREVIEW</p><div class="mini-page"><div class="mini-brand">${esc(state.brand.name.toUpperCase())}</div><div class="mini-heading">${esc(state.brand.tagline)}</div><p style="text-align:center;font-size:10px;color:var(--muted);margin-bottom:18px">${esc(state.brand.intro)}</p>${coverCard()}${state.sections.filter(s=>s.visible).map(s=>{let list=state.stories.filter(t=>s.id==='people'?t.category==='Our Stories':s.id==='pieces'?t.category==='Behind the Pieces':s.id==='culture'?t.category==='Culture':t.id==='nynth-perspective');list.sort((a,b)=>Number(b.featured)-Number(a.featured)||(b.author===state.brand.editor)-(a.author===state.brand.editor));return `<div class="mini-section"><h3>${esc(s.title)}</h3><div class="mini-cards">${list.slice(0,3).map(t=>`<div>${photo(t.image,'',t.title)}<span>${esc(t.title)}</span></div>`).join('')}</div>`}).join('')}</div></div></div>`}
function media(){return heading('THE VISUAL WORLD','Let the pictures speak.','A home for campaign shots, portraits, and the details that matter.','<button class="button" data-action="upload">↑ Upload image</button>')+`<p class="form-hint">Demo uploads stay on this device. JPEG, PNG or WebP · up to 1 MB each · 3 MB total for local uploads.</p><div class="media-grid">${state.media.map((m,i)=>`<article class="media-card reveal" style="--i:${Math.min(i,5)}"><div class="media-picture">${photo(m.url,'',m.name)}</div><div class="media-meta"><strong>${esc(m.name)}</strong><small>${m.local?'Your local demo upload':'NYNTH image'} · Ready for a story</small><button class="text-button" data-action="use-image" data-id="${esc(m.id)}">Create story with image ↗</button></div></article>`).join('')}</div>`}
function submissions(){return heading('COMMUNITY DESK','Different voices. One world.','Review the stories people want to share with NYNTH.')+`<section class="panel reveal"><div class="panel-head"><div><h2>From the community.</h2><p>These are fictional submissions for testing the review flow.</p></div></div>${state.submissions.map(s=>`<article class="submission"><div>${badge(s.status)}<h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p><small style="margin-top:10px">${esc(s.author)} · ${esc(s.category)}</small></div><div class="submission-actions"><button class="button secondary" data-action="review" data-id="${s.id}">Read submission</button>${s.status==='Pending'?`<button class="button" data-action="accept" data-id="${s.id}">Accept as draft ↗</button><button class="text-button" data-action="decline" data-id="${s.id}">Decline</button>`:''}</div></article>`).join('')}</section>`}
function settings(){return heading('THE BRAND','Make it unmistakably NYNTH.','Shape the words that introduce your world.')+`<section class="panel reveal"><form class="settings-form" id="settings-form"><h2>The essentials.</h2><label for="brand-name">Brand name</label><input id="brand-name" value="${esc(state.brand.name)}" maxlength="80" required><label for="brand-tagline">Slogan</label><input id="brand-tagline" value="${esc(state.brand.tagline)}" maxlength="100" required><label for="brand-intro">Journal introduction</label><textarea id="brand-intro" maxlength="300" rows="3">${esc(state.brand.intro)}</textarea><label for="brand-editor">Editor’s name</label><input id="brand-editor" value="${esc(state.brand.editor)}" maxlength="80" required><p class="form-hint">These settings update the demo homepage and the default author for new stories.</p><button class="button" type="submit">Save brand settings ↗</button></form></section>`}
function render(){document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$('#page-label').textContent=({overview:'Overview',stories:'Stories',homepage:'Homepage',media:'Media library',submissions:'Submissions',settings:'Brand settings'})[view];$('#story-count').textContent=state.stories.length;$('#submission-count').textContent=state.submissions.filter(s=>s.status==='Pending').length;$('#content').innerHTML=({overview,stories:storiesView,homepage,media,submissions,settings})[view]();}
function navigate(next){view=next;render();history.replaceState(null,'','#'+next)}
function openEditor(id,image){const s=state.stories.find(s=>s.id===id)||{id:'',title:'',category:'Our Stories',author:state.brand.editor,summary:'',body:'',image:image||'',status:'Draft',featured:false};$('#editor-title').textContent=s.id?'Give it your perspective.':'Start something worth sharing.';$('#story-id').value=s.id;$('#story-title').value=s.title;$('#story-category').value=s.category;$('#story-author').value=s.author;$('#story-summary').value=s.summary;$('#story-body').value=s.body;coverImage=s.image;$('#story-image').value=s.image==='newman'||s.image.startsWith('data:')?'':s.image;$('#story-status').value=s.status;$('#story-featured').checked=s.featured;$('#editor-error').textContent='';updateCover();$('#editor').showModal()}
function updateCover(){$('#cover-preview').innerHTML=coverImage?photo(coverImage,'','Cover preview'):''}
function showPreview(s){$('#preview-body').innerHTML=`<div class="overline">${esc(s.category)} / DEMO PREVIEW</div><h1 id="preview-title">${esc(s.title)}</h1><small>By ${esc(s.author)}</small><p class="preview-summary">${esc(s.summary)}</p>${photo(s.image,'',s.title)}<p>${esc(s.body)}</p>`;$('#preview').showModal()}
function pickUpload(mode){uploadMode=mode;$('#file-input').value='';$('#file-input').click()}
$('#content').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id,s=state.stories.find(s=>s.id===id);if(action==='go')navigate(b.dataset.target);if(action==='new')openEditor();if(action==='edit')openEditor(id);if(action==='preview'&&s)showPreview(s);if(action==='upload')pickUpload('library');if(action==='use-image')openEditor(null,state.media.find(m=>m.id===id).url);if(action==='filter'){filter=id;render()}if(action==='feature'&&s){s.featured=!s.featured;persist();render();toast(s.featured?'Added to the featured stories in this demo.':'Removed from featured stories.')}if(action.startsWith('move-')){const i=state.sections.findIndex(s=>s.id===id),j=i+(action==='move-up'?-1:1);if(j>=0&&j<state.sections.length){[state.sections[i],state.sections[j]]=[state.sections[j],state.sections[i]];persist();render();toast('Section order updated in the preview.')}}if(action==='toggle-section'){const section=state.sections.find(s=>s.id===id);section.visible=!section.visible;persist();render()}if(['review','accept','decline'].includes(action)){const sub=state.submissions.find(s=>s.id===id);if(action==='review')showPreview(sub);else if(sub.status==='Pending'){sub.status=action==='accept'?'Accepted':'Declined';if(action==='accept')state.stories.unshift({...sub,id:'story-'+Date.now(),status:'Draft',featured:false});persist();render();toast(action==='accept'?'Accepted as a draft. You can edit it in Stories.':'Sample submission declined.')}}});
$('#content').addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;$('#story-results').innerHTML=filteredTable()}});
$('#content').addEventListener('change',e=>{if(e.target.id==='cover-select'){state.cover=e.target.value;persist();render();toast('Cover story updated in this preview.')}});
$('#content').addEventListener('submit',e=>{if(e.target.id==='settings-form'){e.preventDefault();state.brand={name:$('#brand-name').value.trim(),tagline:$('#brand-tagline').value.trim(),intro:$('#brand-intro').value.trim(),editor:$('#brand-editor').value.trim()};persist();toast('Brand settings saved for this demo.')}});
$('#editor-form').addEventListener('submit',e=>{e.preventDefault();const id=$('#story-id').value||'story-'+Date.now();const title=$('#story-title').value.trim(),author=$('#story-author').value.trim();if(!title||!author){$('#editor-error').textContent='Add a title and author before saving.';return}if($('#story-image').value&&!safeImage($('#story-image').value)){$('#editor-error').textContent='Use an image URL beginning with https:// or http://.';return}const s={id,title,author,category:$('#story-category').value,summary:$('#story-summary').value.trim(),body:$('#story-body').value.trim(),image:coverImage,status:$('#story-status').value,featured:$('#story-featured').checked};const i=state.stories.findIndex(s=>s.id===id);if(i<0)state.stories.unshift(s);else state.stories[i]=s;if(state.cover===id&&s.status!=='Published')state.cover=state.stories.find(s=>s.status==='Published')?.id||id;const saved=persist();$('#editor').close();render();if(saved)toast('Story saved in this browser. The live journal is unchanged.');});
$('#story-image').addEventListener('input',e=>{coverImage=safeImage(e.target.value);updateCover()});
$('#choose-cover').addEventListener('click',()=>pickUpload('cover'));
$('#file-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('Choose a JPEG, PNG or WebP image.');return}if(file.size>1024*1024){toast('Choose an image smaller than 1 MB for this demo.');return}const uploaded=state.media.filter(m=>m.local).reduce((n,m)=>n+(m.bytes||0),0);if(uploaded+file.size>3*1024*1024){toast('The demo upload limit is 3 MB. Reset the demo to clear uploads.');return}try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});await new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=reject;img.src=data});state.media.unshift({id:'media-'+Date.now(),url:data,name:file.name,local:true,bytes:file.size});const saved=persist();if(uploadMode==='cover'){coverImage=data;$('#story-image').value='';updateCover()}else{navigate('media')}if(saved)toast('Image added to your local demo library.')}catch{toast('That image could not be read. Try another file.')}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));
$('#help').addEventListener('click',()=>$('#notice').showModal());
$('#reset').addEventListener('click',()=>{if(confirm('Reset this demo? Your local demo edits and uploads will be removed. The live journal will not change.')){state=structuredClone(initial);filter='All';query='';persist();render();toast('Fresh start. The demo has been reset.')}});
if(['overview','stories','homepage','media','submissions','settings'].includes(location.hash.slice(1)))view=location.hash.slice(1);
render();
